
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormaterServiceService", targetNamespace = "http://formater/", wsdlLocation = "file:/users/alumnos-16-17/a0363819/ssdd_assignment_100363788_100363819/FormaterService.wsdl")
public class FormaterServiceService
    extends Service
{

    private final static URL FORMATERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMATERSERVICESERVICE_EXCEPTION;
    private final static QName FORMATERSERVICESERVICE_QNAME = new QName("http://formater/", "FormaterServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/users/alumnos-16-17/a0363819/ssdd_assignment_100363788_100363819/FormaterService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMATERSERVICESERVICE_WSDL_LOCATION = url;
        FORMATERSERVICESERVICE_EXCEPTION = e;
    }

    public FormaterServiceService() {
        super(__getWsdlLocation(), FORMATERSERVICESERVICE_QNAME);
    }

    public FormaterServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMATERSERVICESERVICE_QNAME, features);
    }

    public FormaterServiceService(URL wsdlLocation) {
        super(wsdlLocation, FORMATERSERVICESERVICE_QNAME);
    }

    public FormaterServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMATERSERVICESERVICE_QNAME, features);
    }

    public FormaterServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormaterServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormaterService
     */
    @WebEndpoint(name = "FormaterServicePort")
    public FormaterService getFormaterServicePort() {
        return super.getPort(new QName("http://formater/", "FormaterServicePort"), FormaterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormaterService
     */
    @WebEndpoint(name = "FormaterServicePort")
    public FormaterService getFormaterServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://formater/", "FormaterServicePort"), FormaterService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMATERSERVICESERVICE_EXCEPTION!= null) {
            throw FORMATERSERVICESERVICE_EXCEPTION;
        }
        return FORMATERSERVICESERVICE_WSDL_LOCATION;
    }

}
